import {
  axisRotations,
  planeRotations,
  pColor,
  rotColor,
  axColor,
} from "../../build/AxesProps";

const hexagonalAxes = {
  _6ommm: {
    a1: {
      rotationSym: 2,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.four],
      hasPlane: true,
    },
    a1h: {
      rotationSym: 1,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.two],
      hexagon: true,
      hasPlane: true,
    },
    a2: {
      rotationSym: 2,
      axisRotation: axisRotations.a2,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.four],
      hasPlane: true,
    },
    a3: {
      rotationSym: 2,
      axisRotation: axisRotations.a3,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.four],
      hasPlane: true,
    },
    a12: {
      rotationSym: 2,
      axisRotation: axisRotations.a12,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a13: {
      rotationSym: 2,
      axisRotation: axisRotations.a13,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a23: {
      rotationSym: 2,
      axisRotation: axisRotations.a23,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    z: {
      rotationSym: 6,
      axisRotation: axisRotations.z,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [
        planeRotations.three0,
        planeRotations.three1,
        planeRotations.three2,
      ],
      hasPlane: true,
    },
  },
  _6barm2: {
    a1: {
      rotationSym: 2,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.four],
      hasPlane: true,
    },
    a1h: {
      rotationSym: 1,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.two],
      hexagon: true,
      hasPlane: true,
    },
    a2: {
      rotationSym: 2,
      axisRotation: axisRotations.a2,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.four],
      hasPlane: true,
    },
    a3: {
      rotationSym: 2,
      axisRotation: axisRotations.a3,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.four],
      hasPlane: true,
    },
    z: {
      rotationSym: 6,
      axisRotation: axisRotations.z,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
  },
  _6mm: {
    a1: {
      rotationSym: 1,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.four],
      hasPlane: true,
    },
    a2: {
      rotationSym: 1,
      axisRotation: axisRotations.a2,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.four],
      hasPlane: true,
    },
    a3: {
      rotationSym: 1,
      axisRotation: axisRotations.a3,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.four],
      hasPlane: true,
    },
    a12: {
      rotationSym: 1,
      axisRotation: axisRotations.a12,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a13: {
      rotationSym: 1,
      axisRotation: axisRotations.a13,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a23: {
      rotationSym: 1,
      axisRotation: axisRotations.a23,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    z: {
      rotationSym: 6,
      axisRotation: axisRotations.z,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [
        planeRotations.three0,
        planeRotations.three1,
        planeRotations.three2,
      ],
      hasPlane: true,
    },
  },
  _622: {
    a1: {
      rotationSym: 2,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a2: {
      rotationSym: 2,
      axisRotation: axisRotations.a2,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a3: {
      rotationSym: 2,
      axisRotation: axisRotations.a3,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a12: {
      rotationSym: 2,
      axisRotation: axisRotations.a12,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a13: {
      rotationSym: 2,
      axisRotation: axisRotations.a13,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a23: {
      rotationSym: 2,
      axisRotation: axisRotations.a23,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    z: {
      rotationSym: 6,
      axisRotation: axisRotations.z,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
  },
  _6om: {
    a1: {
      rotationSym: 2,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a1h: {
      rotationSym: 1,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.two],
      hexagon: true,
      hasPlane: true,
    },
    a2: {
      rotationSym: 2,
      axisRotation: axisRotations.a2,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a3: {
      rotationSym: 2,
      axisRotation: axisRotations.a3,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    z: {
      rotationSym: 6,
      axisRotation: axisRotations.z,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
  },
  _6bar: {
    a1: {
      rotationSym: 1,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a1h: {
      rotationSym: 1,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [planeRotations.two],
      hexagon: true,
      hasPlane: true,
    },
    a2: {
      rotationSym: 1,
      axisRotation: axisRotations.a2,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a3: {
      rotationSym: 1,
      axisRotation: axisRotations.a3,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    z: {
      rotationSym: 6,
      axisRotation: axisRotations.z,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
  },
  _6: {
    a1: {
      rotationSym: 1,
      axisRotation: axisRotations.a1,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a2: {
      rotationSym: 1,
      axisRotation: axisRotations.a2,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    a3: {
      rotationSym: 1,
      axisRotation: axisRotations.a3,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
    z: {
      rotationSym: 6,
      axisRotation: axisRotations.z,
      rotationColor: rotColor,
      planeColor: pColor,
      axisColor: axColor,
      planes: [],
      hasPlane: false,
    },
  },
};

export default hexagonalAxes;
